ContextException=Error in {0}
ContextNotFound=Context ''{0}'' not found
ContextAlreadyExists=Context ''{0}'' already exists
RefNotFound={0} not found in {1}
RefAlreadyExists={0} already exists in {1}
FunctionException=Error in function ''{0}'': {1}
